"use client";

import { useState, useEffect } from 'react';
import { usePortfolio, Asset } from '@/context/PortfolioContext';
import { PlusCircle, Search, ArrowLeft, Calendar, DollarSign, BarChart3, Edit3, X } from 'lucide-react';

interface StockMaster {
    symbol: string;
    name: string;
    standard_code: string;
    group_code: string;
}

export default function AddAssetForm() {
    const { addAsset } = usePortfolio();
    const [isOpen, setIsOpen] = useState(false);
    const [view, setView] = useState<'SEARCH' | 'FORM'>('SEARCH');

    // Search State
    const [searchTerm, setSearchTerm] = useState('');
    const [masterData, setMasterData] = useState<StockMaster[]>([]);
    const [searchResults, setSearchResults] = useState<StockMaster[]>([]);
    const [selectedStock, setSelectedStock] = useState<StockMaster | null>(null);

    // Form State
    const [formData, setFormData] = useState({
        // Asset Meta
        targetMemo: '',
        targetLower: '',
        targetUpper: '',

        // Trade Log
        date: new Date().toISOString().split('T')[0],
        type: 'BUY' as 'BUY' | 'SELL',
        price: '',
        quantity: '',
        kospiIndex: '',
        logMemo: ''
    });

    // Load Master Data on Open
    useEffect(() => {
        if (isOpen && masterData.length === 0) {
            fetch('/data/kospi_master.json')
                .then(res => res.json())
                .then(data => setMasterData(data))
                .catch(err => console.error(err));
        }
    }, [isOpen, masterData]);

    // Filter Search
    useEffect(() => {
        if (!searchTerm) {
            setSearchResults([]);
            return;
        }
        const term = searchTerm.toLowerCase();
        const filtered = masterData.filter(item =>
            item.name.toLowerCase().includes(term) || item.symbol.includes(term)
        ).slice(0, 10);
        setSearchResults(filtered);
    }, [searchTerm, masterData]);

    const handleSelectStock = (stock: StockMaster) => {
        setSelectedStock(stock);
        setView('FORM');
    };

    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        if (!selectedStock) return;

        const qty = Number(formData.quantity);
        const price = Number(formData.price);
        const kospi = Number(formData.kospiIndex);

        addAsset({
            symbol: selectedStock.symbol,
            name: selectedStock.name,
            category: 'KR', // Default to KR for KIS Master

            // Asset Summary (Initial Holding)
            quantity: formData.type === 'BUY' ? qty : -qty,
            pricePerShare: price, // For initial entry, use trade price as avg
            purchaseDate: formData.date,
            purchasePurpose: formData.targetMemo, // Mapping Target Memo to legacy purpose field if needed
            purchaseIndexValue: kospi,

            // New Fields
            memo: formData.targetMemo,
            targetPriceLower: formData.targetLower ? Number(formData.targetLower) : undefined,
            targetPriceUpper: formData.targetUpper ? Number(formData.targetUpper) : undefined,

            // Trade Log
            trades: [{
                // id will be generated by DB
                date: formData.date,
                type: formData.type,
                price: price,
                quantity: qty,
                kospiIndex: kospi,
                memo: formData.logMemo
            } as any] // Cast as any temporarily because interface expects ID, but we omit it for new creation
        });

        handleClose();
    };

    const handleClose = () => {
        setIsOpen(false);
        setView('SEARCH');
        setSearchTerm('');
        setSelectedStock(null);
        setFormData({
            targetMemo: '',
            targetLower: '',
            targetUpper: '',
            date: new Date().toISOString().split('T')[0],
            type: 'BUY',
            price: '',
            quantity: '',
            kospiIndex: '',
            logMemo: ''
        });
    };

    return (
        <>
            {/* Trigger Button */}
            <button
                onClick={() => setIsOpen(true)}
                className="flex items-center space-x-2 bg-indigo-600 text-white px-4 py-2 rounded-lg hover:bg-indigo-700 transition shadow-sm hover:shadow"
            >
                <Edit3 size={18} />
                <span>내 주식 기록하기</span>
            </button>

            {/* Modal Overlay */}
            {isOpen && (
                <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/50 backdrop-blur-sm p-4 animate-in fade-in duration-200">
                    <div className="bg-white rounded-2xl w-full max-w-2xl shadow-2xl flex flex-col max-h-[90vh] overflow-hidden animate-in zoom-in-95 duration-200">
                        {/* Header */}
                        <div className="p-4 border-b border-slate-100 flex justify-between items-center bg-slate-50/50">
                            <h3 className="text-lg font-bold text-slate-800 flex items-center gap-2">
                                {view === 'SEARCH' ? (
                                    <>
                                        <Search size={20} className="text-indigo-600" />
                                        <span>종목 검색</span>
                                    </>
                                ) : (
                                    <>
                                        <button
                                            onClick={() => setView('SEARCH')}
                                            className="mr-2 text-slate-400 hover:text-slate-600 transition"
                                        >
                                            <ArrowLeft size={20} />
                                        </button>
                                        <span>매매 상세 기록</span>
                                    </>
                                )}
                            </h3>
                            <button onClick={handleClose} className="p-2 hover:bg-slate-200 rounded-full transition text-slate-500">
                                <X size={20} />
                            </button>
                        </div>

                        {/* Body - Scrollable */}
                        <div className="flex-1 overflow-y-auto p-6">
                            {view === 'SEARCH' ? (
                                // SEARCH VIEW
                                <div>
                                    <div className="relative mb-6">
                                        <input
                                            type="text"
                                            placeholder="종목명 또는 코드 (예: 삼성전자)"
                                            className="w-full p-4 pl-12 border border-slate-300 rounded-xl focus:ring-2 focus:ring-indigo-500 outline-none text-lg shadow-sm"
                                            value={searchTerm}
                                            onChange={(e) => setSearchTerm(e.target.value)}
                                            autoFocus
                                        />
                                        <Search className="absolute left-4 top-4.5 text-slate-400" size={24} />
                                    </div>

                                    {/* Results List */}
                                    <div className="space-y-2">
                                        {searchResults.length > 0 ? (
                                            searchResults.map(stock => (
                                                <button
                                                    key={stock.symbol}
                                                    onClick={() => handleSelectStock(stock)}
                                                    className="w-full text-left p-4 hover:bg-slate-50 border border-transparent hover:border-indigo-100 rounded-xl flex justify-between items-center group transition"
                                                >
                                                    <div>
                                                        <div className="font-bold text-slate-800 text-lg">{stock.name}</div>
                                                        <div className="text-sm text-slate-400 font-mono">{stock.symbol}</div>
                                                    </div>
                                                    <div className="text-indigo-600 opacity-0 group-hover:opacity-100 transition flex items-center gap-1 font-medium bg-indigo-50 px-3 py-1 rounded-full text-sm">
                                                        선택 <ArrowLeft className="rotate-180" size={14} />
                                                    </div>
                                                </button>
                                            ))
                                        ) : (
                                            searchTerm ? (
                                                <div className="text-center text-slate-400 py-12 flex flex-col items-center">
                                                    <Search size={48} className="mb-4 text-slate-200" />
                                                    <span>검색 결과가 없습니다.</span>
                                                </div>
                                            ) : (
                                                <div className="text-center text-slate-400 py-12 flex flex-col items-center">
                                                    <div className="w-16 h-1 bg-slate-100 rounded-full mb-4"></div>
                                                    <span>종목을 검색하여 선택하세요.</span>
                                                </div>
                                            )
                                        )}
                                    </div>
                                </div>
                            ) : (
                                // FORM VIEW
                                <form onSubmit={handleSubmit} className="space-y-8">
                                    {/* Selected Stock Banner */}
                                    <div className="flex items-center justify-between bg-slate-50 p-4 rounded-xl border border-slate-100">
                                        <div>
                                            <div className="text-2xl font-bold text-slate-900">{selectedStock?.name}</div>
                                            <div className="text-sm text-slate-500 font-mono mt-0.5">{selectedStock?.symbol}</div>
                                        </div>
                                        <span className="text-xs font-bold text-indigo-600 bg-indigo-50 px-3 py-1 rounded-full border border-indigo-100">New Entry</span>
                                    </div>

                                    <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                                        {/* Left: Targets */}
                                        <div className="space-y-5">
                                            <div className="flex items-center gap-2 text-slate-800 font-bold border-b border-slate-100 pb-2">
                                                <div className="w-1 h-5 bg-red-500 rounded-full"></div>
                                                목표 설정 (Target)
                                            </div>

                                            <div>
                                                <label className="block text-sm font-medium text-slate-600 mb-1.5">목표 메모</label>
                                                <input
                                                    type="text"
                                                    placeholder="예: 배당 및 장기 보유"
                                                    className="w-full p-3 border border-slate-300 rounded-lg focus:ring-2 focus:ring-indigo-500 outline-none transition"
                                                    value={formData.targetMemo}
                                                    onChange={(e) => setFormData({ ...formData, targetMemo: e.target.value })}
                                                />
                                            </div>
                                            <div className="grid grid-cols-2 gap-4">
                                                <div>
                                                    <label className="block text-sm font-medium text-slate-600 mb-1.5">매도 하한</label>
                                                    <input
                                                        type="number"
                                                        placeholder="0"
                                                        className="w-full p-3 border border-slate-300 rounded-lg focus:ring-2 focus:ring-indigo-500 outline-none transition text-right font-mono"
                                                        value={formData.targetLower}
                                                        onChange={(e) => setFormData({ ...formData, targetLower: e.target.value })}
                                                    />
                                                </div>
                                                <div>
                                                    <label className="block text-sm font-medium text-slate-600 mb-1.5">매도 상한</label>
                                                    <input
                                                        type="number"
                                                        placeholder="0"
                                                        className="w-full p-3 border border-slate-300 rounded-lg focus:ring-2 focus:ring-indigo-500 outline-none transition text-right font-mono"
                                                        value={formData.targetUpper}
                                                        onChange={(e) => setFormData({ ...formData, targetUpper: e.target.value })}
                                                    />
                                                </div>
                                            </div>
                                        </div>

                                        {/* Right: Trade Log */}
                                        <div className="space-y-5">
                                            <div className="flex items-center gap-2 text-slate-800 font-bold border-b border-slate-100 pb-2">
                                                <div className="w-1 h-5 bg-blue-500 rounded-full"></div>
                                                첫 매매 기록 (Log)
                                            </div>

                                            <div className="grid grid-cols-2 gap-4">
                                                <div>
                                                    <label className="block text-sm font-medium text-slate-600 mb-1.5">일자</label>
                                                    <div className="relative">
                                                        <input
                                                            required
                                                            type="date"
                                                            className="w-full p-3 pl-10 border border-slate-300 rounded-lg focus:ring-2 focus:ring-indigo-500 outline-none transition text-sm"
                                                            value={formData.date}
                                                            onChange={(e) => setFormData({ ...formData, date: e.target.value })}
                                                        />
                                                        <Calendar className="absolute left-3 top-3.5 text-slate-400" size={16} />
                                                    </div>
                                                </div>
                                                <div>
                                                    <label className="block text-sm font-medium text-slate-600 mb-1.5">구분</label>
                                                    <div className="flex bg-slate-100 rounded-lg p-1 h-[46px]">
                                                        <button
                                                            type="button"
                                                            onClick={() => setFormData({ ...formData, type: 'BUY' })}
                                                            className={`flex-1 text-sm rounded-md transition font-medium ${formData.type === 'BUY' ? 'bg-white text-red-600 shadow-sm border border-slate-200' : 'text-slate-500 hover:text-slate-700'}`}
                                                        >
                                                            매수
                                                        </button>
                                                        <button
                                                            type="button"
                                                            onClick={() => setFormData({ ...formData, type: 'SELL' })}
                                                            className={`flex-1 text-sm rounded-md transition font-medium ${formData.type === 'SELL' ? 'bg-white text-blue-600 shadow-sm border border-slate-200' : 'text-slate-500 hover:text-slate-700'}`}
                                                        >
                                                            매도
                                                        </button>
                                                    </div>
                                                </div>
                                            </div>

                                            <div className="grid grid-cols-2 gap-4">
                                                <div>
                                                    <label className="block text-sm font-medium text-slate-600 mb-1.5">가격 (단가)</label>
                                                    <input
                                                        required
                                                        type="number"
                                                        className="w-full p-3 border border-slate-300 rounded-lg focus:ring-2 focus:ring-indigo-500 outline-none transition text-right font-mono"
                                                        placeholder="0"
                                                        value={formData.price}
                                                        onChange={(e) => setFormData({ ...formData, price: e.target.value })}
                                                    />
                                                </div>
                                                <div>
                                                    <label className="block text-sm font-medium text-slate-600 mb-1.5">수량</label>
                                                    <input
                                                        required
                                                        type="number"
                                                        className="w-full p-3 border border-slate-300 rounded-lg focus:ring-2 focus:ring-indigo-500 outline-none transition text-right font-mono"
                                                        placeholder="0"
                                                        value={formData.quantity}
                                                        onChange={(e) => setFormData({ ...formData, quantity: e.target.value })}
                                                    />
                                                </div>
                                            </div>

                                            <div className="grid grid-cols-2 gap-4">
                                                <div>
                                                    <label className="block text-sm font-medium text-slate-600 mb-1.5">KOSPI 지수</label>
                                                    <input
                                                        type="number"
                                                        className="w-full p-3 border border-slate-300 rounded-lg focus:ring-2 focus:ring-indigo-500 outline-none transition text-right font-mono"
                                                        placeholder="예: 2500"
                                                        value={formData.kospiIndex}
                                                        onChange={(e) => setFormData({ ...formData, kospiIndex: e.target.value })}
                                                    />
                                                </div>
                                                <div>
                                                    <label className="block text-sm font-medium text-slate-600 mb-1.5">매매 메모</label>
                                                    <input
                                                        type="text"
                                                        className="w-full p-3 border border-slate-300 rounded-lg focus:ring-2 focus:ring-indigo-500 outline-none transition"
                                                        placeholder="특이사항..."
                                                        value={formData.logMemo}
                                                        onChange={(e) => setFormData({ ...formData, logMemo: e.target.value })}
                                                    />
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    {/* Action Buttons */}
                                    <div className="pt-6 border-t border-slate-100 flex justify-end gap-3 sticky bottom-0 bg-white pb-2">
                                        <button
                                            type="button"
                                            onClick={handleClose}
                                            className="px-6 py-3 text-slate-500 font-medium hover:bg-slate-50 rounded-xl transition"
                                        >
                                            취소
                                        </button>
                                        <button
                                            type="submit"
                                            className="bg-slate-900 text-white px-8 py-3 rounded-xl hover:bg-slate-800 transition font-bold shadow-lg hover:shadow-xl transform active:scale-95 duration-200"
                                        >
                                            저장하기
                                        </button>
                                    </div>
                                </form>
                            )}
                        </div>
                    </div>
                </div>
            )}
        </>
    );
}
