-- 포트폴리오 일일 스냅샷 이력을 저장하는 테이블
CREATE TABLE IF NOT EXISTS public.portfolio_daily_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    record_date DATE NOT NULL,
    total_investment NUMERIC DEFAULT 0,
    total_valuation NUMERIC DEFAULT 0,
    assets_snapshot JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(user_id, record_date)
);

-- RLS (Row Level Security) 설정
ALTER TABLE public.portfolio_daily_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own portfolio history" 
ON public.portfolio_daily_history FOR SELECT 
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own portfolio history" 
ON public.portfolio_daily_history FOR INSERT 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own portfolio history" 
ON public.portfolio_daily_history FOR UPDATE 
USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own portfolio history" 
ON public.portfolio_daily_history FOR DELETE 
USING (auth.uid() = user_id);

-- 인덱스 생성 (조회 속도 향상)
CREATE INDEX IF NOT EXISTS idx_portfolio_daily_history_user_id ON public.portfolio_daily_history(user_id);
CREATE INDEX IF NOT EXISTS idx_portfolio_daily_history_record_date ON public.portfolio_daily_history(record_date);
